###
GET http://localhost:8080

###
GET http://localhost:8080/cate
Accept: application/jsonhttps://github.com/Saraosp25/cates/blob/main/cates.http

###
POST http://localhost:8080/cate
Accept: application/json

{
    "name":"Sara1",
    
}

###
PUT http://localhost:8080/cate/1
Accept: application/json
{
   "name":"Sara2000",
   
}

###
DELETE http://localhost:8080/cate/1 
Accept: application/json
